spring:
  application:
    name: chupapo-api

  datasource:
    url: jdbc:postgresql://localhost:5432/chupapo
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
